parameters:
  serviceConnection: ''
  aksResourceGroup: ''
  aksClusterName: ''
  minCount: '1'
  maxCount: '3'
  
steps:
- task: AzureCLI@1
  displayName: 'Enable Cluster Autosclaer'
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks update \
        --resource-group ${{ parameters.aksResourceGroup }} \
        --name ${{ parameters.aksClusterName }} \
        --enable-cluster-autoscaler \
        --min-count ${{ parameters.minCount }} \
        --max-count ${{ parameters.maxCount }}