apiserver:
  resources:
    requests:
      cpu: 150m
      memory: 40Mi
    limits:
      cpu: 600m
      memory: 600Mi
  storage:
    etcd:
      persistence:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
  healthcheck:
    enabled: false
controllerManager:
  healthcheck:
    enabled: false
