pool:
  vmImage: 'Ubuntu 16.04'

variables:
  kubectlConnectionType: 'Azure Resource Manager'
  aksResourceGroup: 'cnp-aks-sandbox-rg'
  clusterName: 'cnp-aks-sandbox-cluster'
  environment: 'sandbox'
  
steps:
- template: reinstall-traefik-template.yml
  parameters:
    serviceConnection: azurerm-sandbox