# see https://dev.azure.com/hmcts/CNP/_build?definitionId=254&_a=summary
---
name: AKS Monitor AAT 00 Helm Releases
trigger: none
pr: none
schedules:
- cron: '0 */2 * * *'
  displayName: Monitor releases every 2 hour
  branches:
    include:
      - master
  always: 'true'

jobs:
  - template: template.yaml
    parameters:
      azureResourceGroup: 'aat-00-rg'
      kubernetesCluster: 'aat-00-aks'
      helmVersion: '2.15.2'
      azureSubscription: 'DCD-CFTAPPS-STG'
      vaultName: 'cftapps-stg'
      enableHelmTls: 'true'
