parameters:
  serviceConnection: ''
  keyvaultName: ''
  aksResourceGroup: ''
  aksClusterName: ''
  aksParametersFile: ''
  minNodeCount: ''
  maxNodeCount: ''

jobs:
- job: DeployAKS
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Get AKS Service Principal Secrets from Keyvault'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      keyVaultName: ${{ parameters.keyvaultName }}
      secretsFilter: 'aks-sp-id,aks-sp-secret'
  - template: ../tasks/deploy-aks-arm.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksParametersFile: ${{ parameters.aksParametersFile }}
      aksServicePrincipalId: $(aks-sp-id)
      aksServicePrincipalSecret: $(aks-sp-secret)
  - template: ../tasks/enable-aks-autoscaler.yaml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      aksResourceGroup: ${{ parameters.aksResourceGroup }}
      aksClusterName: ${{ parameters.aksClusterName }}
      minCount: ${{ parameters.minNodeCount }}
      maxCount: ${{ parameters.maxNodeCount }}