#
# Gets Keyvault secrets and maps them to variables expected by subsequent jobs
#
# For builds creating a CI (Jenkins) cluster
#
parameters:
  serviceConnection: ''

jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Get secrets from Keyvault'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      keyVaultName: $(keyvaultName)
      secretsFilter: 'aks-mgmt-sp-id,aks-mgmt-sp-secret,mgmt-sandbox-flux-git-deploy,mgmt-sandbox-sealed-secret-key,mgmt-sandbox-sealed-secret-crt'

  - script: |
      echo "##vso[task.setvariable variable=aksServicePrincipalId;isOutput=true]$(aks-mgmt-sp-id)"
      echo "##vso[task.setvariable variable=aksServicePrincipalSecret;isOutput=true]$(aks-mgmt-sp-secret)"
      echo "##vso[task.setvariable variable=mgmtSandboxFluxGitDeploy;isOutput=true]$(mgmt-sandbox-flux-git-deploy)"
      echo "##vso[task.setvariable variable=mgmtSandboxSealedSecretKey;isOutput=true]$(mgmt-sandbox-sealed-secret-key)"
      echo "##vso[task.setvariable variable=mgmtSandboxSealedSecretCrt;isOutput=true]$(mgmt-sandbox-sealed-secret-crt)"
    displayName: 'Translate Keyvault Variables'
    name: exportKeyvault
