---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cnp-osba-postgres-server
  namespace: cnp
spec:
  clusterServiceClassExternalName: azure-postgresql-9-6-dbms
  clusterServicePlanExternalName: general-purpose
  parameters:
    location: uksouth
    resourceGroup: cnp-aks-sandbox-rg
    alias: cnp-osba-postgres-server
    cores: 2
    storage: 50
    tags:
      Team Name: CNP