name: Install Pact Broker (prod)
trigger: none

pool:
  vmImage: "Ubuntu 16.04"

variables:
  serviceConnection: azurerm-prod
  acrServiceConnection: azurerm-nonprod
  acrName: hmcts
  kubectlConnectionType: "Azure Resource Manager"
  aksResourceGroup: "cnp-aks-mgmt-rg"
  clusterName: "cnp-aks-mgmt-prod-cluster"
  keyvaultName: "infra-vault-prod"
  ingressHost: pact-broker.platform.hmcts.net
  resourceGroup: "pact-broker-mgmt"
  helmVersion: '2.12.0'

steps:
  - template: ../../steps/install-pact-broker.yml
      