name: Install Pact Broker (prod)
trigger: none

pool:
  vmImage: "Ubuntu 16.04"

variables:
  serviceConnection: azurerm-prod
  kubectlConnectionType: "Azure Resource Manager"
  aksResourceGroup: "cnp-aks-mgmt-rg"
  clusterName: "cnp-aks-mgmt-prod-cluster"
  keyvaultName: "infra-vault-prod"
  ingressHost: chart-pact-broker.service.core-compute-preview.internal
  resourceGroup: "pact-broker-sandbox-mgmt"
  helmVersion: '2.12.0'

steps:
  - template: ../../steps/install-pact-broker.yml
      