name: Install Pact Broker (sandbox)
trigger: none

pool:
  vmImage: "Ubuntu 16.04"

variables:
  serviceConnection: azurerm-sandbox
  kubectlConnectionType: "Azure Resource Manager"
  aksResourceGroup: "cnp-aks-mgmt-rg"
  clusterName: "cnp-aks-mgmt-sandbox-cluster"
  keyvaultName: "infra-vault-sandbox"
  ingressHost: pact-broker.service.core-compute-saat.internal
  resourceGroup: "pact-broker-mgmt"
  helmVersion: '2.12.0'

steps:
  - template: ../../steps/install-pact-broker.yml
