name: Test AKS Pipeline (Cluster Only)
trigger: none
jobs:
- template: ../jobs/aks-cluster-only.yaml
  parameters:
    serviceConnection: azurerm-sandbox
    keyvaultName: infra-vault-sandbox
    aksResourceGroup: cnp-test-aks-rg
    aksClusterName: cnp-test-cluster
    aksParametersFile: arm/parameters/aks/test.json