---

variables:
  vmImage: 'Ubuntu 16.04'
  connectionType: 'Azure Resource Manager'
  azureSubscriptionEndpoint: 'azurerm-aks-nonprod'
  azureResourceGroup: 'cnp-aks-rg'
  kubernetesCluster: 'cnp-aks-cluster'


jobs:
  - job: 'Delete namespace'
    pool:
      vmImage: $(vmImage)
    steps:
    - template: ../steps/kube-delete-namespace.yml
      parameters:
        serviceConnection: azurerm-nonprod
  
