name: Register Consul (DCD-CFTAPPS-TEST-00)
trigger: none
pr: none

jobs:
  - template: template.yaml
    parameters:
      serviceName: $(serviceName)
      serviceAddress: 10.10.41.250
      consulAddress: 10.112.139.254
      agentPool: hmcts-agent-pool
