name: Register Consul (DCD-CFTAPPS-TEST)
trigger: none
pr: none

jobs:
  - template: template.yaml
    parameters:
      serviceName: $(serviceName)
      serviceAddress: 10.10.46.121
      consulAddress: 10.112.139.254
      agentPool: hmcts-agent-pool
