parameters:
  serviceConnection: ''

steps:

- task: HelmDeploy@0
  displayName: 'Install Traefik'
  enabled: true
  inputs:
    connectionType: $(kubectlConnectionType)
    azureSubscription: ${{ parameters.serviceConnection }}
    azureResourceGroup: $(aksResourceGroup)
    kubernetesCluster: $(clusterName)
    command: 'install'
    chartType: 'Name'
    chartName: 'stable/traefik'
    namespace: 'kube-system'
    releaseName: 'traefik'
    valueFile: 'helm/$(environment)/traefik.yml'