helmOperator:
    create: true
    chartsSyncInterval: 1m
    configureRepositories:
      enable: true
registry:
  acr:
    enabled: true
git:
  url: git@github.com:hmcts/cnp-flux-config
  path: k8s/sandbox,k8s/common
  label: sandbox
  pollInterval: 1m
additionalArgs:
- --connect=ws://fluxcloud